---
- hosts: "{{ hosts }}"
  remote_user: "{{ remote_user }}"
  roles:
  - base

- hosts: "{{ hosts }}"
  remote_user: "{{ remote_user }}"
  sudo: yes
  vars:
    rvm1_rubies:
    - 'ruby-1.9.3'
    rvm1_rvm_version: 'stable'
    rvm1_rvm_check_for_updates: true
  roles:
  - rvm_io.rvm1-ruby
