---
- hosts: "{{ hosts }}"
  remote_user: "{{ remote_user }}"
  roles:
  - base

- hosts: "{{ hosts }}"
  remote_user: "{{ remote_user }}"
  sudo: yes
  vars:
    rvm1_rubies:
    - 'ruby-2.0.0'
    rvm1_rvm_version: 'stable'
    rvm1_rvm_check_for_updates: True
  roles:
  - rvm_io.rvm1-ruby

- hosts: "{{ hosts }}"
  remote_user: "{{ remote_user }}"
  sudo: yes
  roles:
  - github-pages